language: java
jdk:
  - oraclejdk8
before_install: find /usr/lib/jvm -name rt.jar
install: ant ivy-get
script: ant test publish
notifications:
  email:
    recipients:
      - secure: "Lb048X11WIBVwRjvDkxz2Zv9Apqb1j5ZfBKDCDN9U1resiTaN5HWpxR4DUWWxLS2DTnIPwJCM8sD8OX812Bk3je5AxXZFEqW//z/2TiOO/VIJ1Bwd5ll1EFyA1rPuns93opv0Q3LiOlNIXFyILJ72kyCWZdkGuQV22YqFEmxj5c="
    on_success: always
