language: java
jdk:
  - oraclejdk8
  - oraclejdk7
before_install: find /usr/lib/jvm -name rt.jar
install: ant ivy-get
script: ant test publish
notifications:
  email:
    recipients:
      - secure: W/lA3oQfMGFSHwbgR7e9sQ+0z6nXUJR9oGnefjUG7Vu2z5Wnsz0lcXN+A0soAFbm7CzrHMK4sY5V8oiqTl+cZTaULe2FjdFEQo7CffNNMwxtefIgrnpYPW5+6O9SYwja9qyHWeYQ2Kk62qiySbf2DkleBYhjzcmgcNFO4xKXa+k=
    on_success: always
